### ISSUE TITLE
Argument methods require [ValidatedNotNull]

### ISSUE THREAD

**Issue by jsk95** [ashmind/Argument#1]
Background: https://github.com/OnTopicCMS/OnTopic-Library/commit/b9e0151d8bacd67a49214054fea9a632167676a8

Resolves: https://github.com/ashmind/SqlFake/pull/2

Suggestion: Upgrade Argument to .netstandard 2.1 and add [ValidatedNotNull] to parameters

**Comment by ashmind** [comment]
Is `ValidatedNotNullAttribute` in  .netstandard 2.1? Can only see an internal one:
https://github.com/dotnet/runtime/search?q=ValidatedNotNullAttribute&unscoped_q=ValidatedNotNullAttribute

**Comment by jsk95** [comment]
The warning is coming from FxCop analyzer

**Comment by jsk95** [comment]
Oh right, it's in Microsoft.VisualStudio.Validation

**Comment by ashmind** [comment]
@jsk95 See #2 (can add you as a reviewer once you accept the repo invite)
